### ISSUE TITLE
[PE-D][Tester A] Entry page of the JAR file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113T-T09-2/tp#223]
![image.png](https://raw.githubusercontent.com/DeepanjaliDhawan/ped/main/files/f7149e5e-3cb3-4703-87df-0efff32d0e70.png)

Shows this on entering the JAR file in the CMD

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: DeepanjaliDhawan/ped#1

**Comment by sansders** [comment]
resolved in #257
