### ISSUE TITLE
[PE-D][Tester C] Two name tags and price tags for additem

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-2/tp#229]
When I type the input "/additem -n "Chicken" -p 12.00 -n "Cook" -p 20.00", I expect it to produce the message reminding the users to only have one name and price tag but it still accepts the command

![image.png](https://raw.githubusercontent.com/Mnsd05/ped/main/files/d0919a9b-b04f-479c-8597-9dd69cc86bb7.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Mnsd05/ped#2

**Comment by nigelhao** [comment]
Issue solved in commit #268
