### ISSUE TITLE
[PE-D][Tester B] Multiple success messages printed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-2/tp#242]
![Screen Shot 2023-03-31 at 5.24.25 PM.png](https://raw.githubusercontent.com/JangusRoundstone/ped/main/files/83ac68b8-d89e-405a-a3e2-9d19e03601c7.png)

It seems here that the number of times of printing the findsuccess message is dependent on the number of items containing the keyword used in finding. I don't believe this is the intended result?

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: JangusRoundstone/ped#3

**Comment by natashatanyt** [comment]
Closing this as it is a duplicate bug report
